### ISSUE TITLE
How to add Syntax Highlighting for java?

### ISSUE THREAD

**Issue by ericbv** [dimpu/ngx-md#122]
I'm trying to add syntax highlighting for java but i can't figure it out.

**Comment by AlphaIX** [comment]
I have the same problem, have you solved it?

**Comment by edodso2** [comment]
Currently it seems like syntax highlighting is only working for JS and CSS because the additional languages import was commented out in `markdown.component.ts `. As a test, I cloned the repo onto my local uncommented and built and all the syntax highlighting works.

Could someone from the project jump in here? It seems this was originally commented out for AOT but Im not having any AOT issues with the above mentioned file uncommented.

**Comment by dimpu** [comment]
@ericbv 
That's very easy

Just add

```ts
import 'prismjs/components/prism-java';
```
in your component or module

I already mentioned about it in the Read me.
